loi_todo/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('todo.urls'))
]

todo/urls.py
from django.conf.urls import url

from . import views

app_name="todo"

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^create', views.create, name="create"),
    url(r'^store', views.store, name="store"),
    url(r'^destroy', views.destroy, name="destroy"),
    url(r'^edit/(?P<id>[0-9]+)/$', views.edit, name="edit"),
    url(r'^update/(?P<id>[0-9]+)/$', views.update, name="update"),
]

todo/models.py
from __future__ import unicode_literals

from django.db import models
import datetime

# Create your models here.
class Todo(models.Model):
    name = models.CharField(max_length=250, unique=True)
    description = models.TextField()
    created_at = models.DateTimeField(default=datetime.datetime.now)
    def __unicode__(self):
        return self.name

todo/forms.py
from django import forms

from todo.models import Todo

class TodoForm(forms.ModelForm):
    class Meta(object):
        model = Todo
        fields = ['name', 'description']

todo/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render
from django.http import HttpResponseRedirect
from models import Todo
from forms import TodoForm

# Create your views here.

def index(request):
	items = Todo.objects.all()
	return render(request, 'todo/index.html', {'items': items})

def create(request):
	form = TodoForm()
	return render(request, 'todo/create.html', {'form': form})

def store(request):
	todoObj = Todo()
	todoObj.name = request.POST.get('name', None)
	todoObj.description = request.POST.get('description', None)
	todoObj.save()
	return HttpResponseRedirect('/')

def destroy(request):
	id = request.POST['id']
	todoObj = Todo.objects.get(pk = id)
	todoObj.delete()
	return HttpResponseRedirect('/')

def edit(request, id):
	todoObj = Todo.objects.get(pk = id)
	form = TodoForm(instance = todoObj)
	return render(request, 'todo/edit.html', {'form': form, 'id': id})

def update(request, id):
	todoObj = Todo.objects.get(pk = id)
	todoObj.name = request.POST.get('name', None)
	todoObj.description = request.POST.get('description', None)
	todoObj.save()
	return HttpResponseRedirect('/')

todo/templates/todo/create.html
{% extends "todo/layout.html" %}

{% block title %}
<title>Create new Todo</title>
{% endblock %}

{% block content %}
    <form action="{% url 'todo:store' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit"> Create </button>
    </form>
{% endblock %}

todo/templates/todo/edit.html
{% extends "todo/layout.html" %}

{% block title %}
<title>Edit</title>
{% endblock %}

{% block content %}
    <form action="{% url 'todo:update' id %}" method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit"> Update </button>
    </form>
{% endblock %}

todo/templates/todo/index.html
{% extends "todo/layout.html" %}

{% block title %}
<title>Todo App</title>
{% endblock %}

{% block content %}
    {% for x in items %}
        <h3>{{ x.name }}</h3>
        <p>{{ x.created_at|date:"D d M Y" }}</p>
        <p>{{ x.description }}</p>
        <a href="{% url 'todo:edit' x.id %}">
            <button type="submit">Edit</button>
        </a>
        <form action="{% url 'todo:destroy' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="id" value="{{ x.id }}">
            <button type="submit">Finish</button>
        </form>
        <hr>
    {% endfor %}
    <a href="{% url 'todo:create' %}">
        <button type="submit">Create new Todo</button>
    </a>
{% endblock %}

todo/templates/todo/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}{% endblock %}
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>